[package]
name = "jacket_process"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
imageproc = "0.25.0"
clap = { version = "4.5.28", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
debug = false
